### PR TITLE
Some torrents have empty url-lists which results to an exception

### PR DESCRIPTION
**Pull request by ualtinok**
Some torrents may have empty url-list like
'8:url-list0:e'

This pull request handles those cases, also have a test for it.

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR! Good catch.

Please remove the `.gitignore` file from this PR and I'll merge it. Everyone should just keep their own global `.gitignore` with `node_modules` in it rather than adding an ignore file to all the modules on npm. :)

**Comment by ualtinok** [comment]
Oh sorry I removed it.

**Comment by feross** [comment]
This PR actually throws an exception when running the tests:

```
# parse url-list for webseed support

/Users/feross/code/parse-torrent-file/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Object true has no method 'map'
    at decodeTorrentFile (/Users/feross/code/parse-torrent-file/index.js:67:88)
    at Test.<anonymous> (/Users/feross/code/parse-torrent-file/test/webseed.js:8:17)
    at Test.bound [as _cb] (/Users/feross/code/parse-torrent-file/node_modules/tape/lib/test.js:59:32)
    at Test.run (/Users/feross/code/parse-torrent-file/node_modules/tape/lib/test.js:72:10)
    at Test.bound [as run] (/Users/feross/code/parse-torrent-file/node_modules/tape/lib/test.js:59:32)
    at Object.next [as _onImmediate] (/Users/feross/code/parse-torrent-file/node_modules/tape/lib/results.js:66:15)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

The automatic CI tests weren't running or this would have been caught immediately when you submitted the PR. I just fixed it so the tests will run on PRs now.

I'll just fix up this PR and merge. Thanks for getting this started.

**Comment by feross** [comment]
Fixed and released as 2.1.1.

**Pull request closed without merging**
